### ISSUE TITLE
504 Gateway

### ISSUE THREAD

**Issue by phamxtien** [ClassmateLin/free-chatgpt#2]
It returns:
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by ClassmateLin** [comment]
Please retry.

> It returns:
> 
> ```
> <html>
> <head><title>504 Gateway Time-out</title></head>
> <body>
> <center><h1>504 Gateway Time-out</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> ```

please retry.
