### ISSUE TITLE
请问将来会引入openai提供的其它api接口吗？

### ISSUE THREAD

**Issue by JiewenGuan** [ClassmateLin/free-chatgpt#3]
比如 https://platform.openai.com/docs/guides/embeddings/what-are-embeddings 这里提供的用于分析文本相似度的embedding

**Comment by ClassmateLin** [comment]
vercel 只提供了chat completion，无法支持

**Comment by ClassmateLin** [comment]
> 比如 https://platform.openai.com/docs/guides/embeddings/what-are-embeddings 这里提供的用于分析文本相似度的embeddingchat completion

**Comment by ClassmateLin** [comment]
> 比如 https://platform.openai.com/docs/guides/embeddings/what-are-embeddings 这里提供的用于分析文本相似度的embedding

vercel 只提供了chat completion, 所以无法支持
